import {createSignal} from "solid-js";
import {createStore} from "solid-js/store";
import {User} from "../../../dto/User";
import {Store} from "../../../dto/Store";
import {Category} from "../../../dto/Category";
import {Adds} from "../../../dto/Adds";

export const [users, setUsers] = createStore<User[]>([]);
export const [renderedUsers, setRenderedUsers] = createStore<User[]>([]);
export const [usersStores, setUsersStores] = createSignal<any[]>([]);
export const [stores, setStores] = createStore<Store[]>([]);
export const [renderedStores, setRenderedStores] = createStore<Store[]>([]);
export const [categories, setCategories] = createStore<Category[]>([]);
export const [renderedCategories, setRenderedCategories] = createStore<Category[]>([]);
export const [adds, setAdds] = createStore<Adds[]>([]);
export const [renderedAdds, setRenderedAdds] = createStore<Adds[]>([]);
export const [availableLanguages, setAvailableLanguages] = createSignal<any[]>([]);
export const [renderedLanguageList, setRenderedLanguageList] = createStore<any[]>([]);
export const [languages, setLanguages] = createStore<any[]>([]);
export const [searchLanguage, setSearchLanguage] = createSignal<string>("");
export const [searchUser, setSearchUser] = createSignal<string>("");
export const [searchStore, setSearchStore] = createSignal<string>("");
export const [searchCategory, setSearchCategory] = createSignal<string>("");
export const [searchAdd, setSearchAdd] = createSignal<string>("");
