import {createSignal} from "solid-js";
import {Store} from "../../../dto/Store";

export const [openAddModal, setOpenAddModal] = createSignal<boolean>(false);
export const [pendingAdd, setPendingAdd] = createSignal<boolean>(false);
export const [openDelete, setOpenDelete] = createSignal<boolean>(false);
export const [pendingDelete, setPendingDelete] = createSignal<boolean>(false);
export const [openEditModal, setOpenEditModal] = createSignal<boolean>(false);
export const [pendingEdit, setPendingEdit] = createSignal<boolean>(false);
export const [syntaxId, setSyntaxId] = createSignal<number>(-1);
export const [syntaxKey, setSyntaxKey] = createSignal<string>("");
export const [syntaxLanguageId, setSyntaxLanguageId] = createSignal<number>(-1);
export const [syntaxValue, setSyntaxValue] = createSignal<string>("");
export const [userId, setUserId] = createSignal<number>(-1);
export const [userNameValue, setUserNameValue] = createSignal<string>("");
export const [passwordValue, setPasswordValue] = createSignal<string>("");
export const [emailValue, setEmailValue] = createSignal<string>("");
export const [storeId, setStoreId] = createSignal<string>("");
export const [typeValue, setTypeValue] = createSignal<string>("");
export const [storeDelete, setStoreDelete] = createSignal<Store | any>({});
export const [storeName, setStoreName] = createSignal<string>("");
export const [storeDescription, setStoreDescription] = createSignal<string>("");
export const [storeEmail, setStoreEmail] = createSignal<string>("");
export const [storeAddress, setStoreAddress] = createSignal<string>("");
export const [storePhone, setStorePhone] = createSignal<string>("");
export const [storeContactId, setStoreContactId] = createSignal<number>(-1);
export const [storeEmailId, setStoreEmailId] = createSignal<number>(-1);
export const [storePhoneId, setStorePhoneId] = createSignal<number>(-1);
export const [storeBannerImage, setStoreBannerImage] = createSignal<string>("");
export const [storeImage, setStoreImage] = createSignal<string>("");
export const [addedStoreId, setAddedStoreId] = createSignal<number>(-1);
export const [addedContactId, setAddedContactId] = createSignal<number>(-1);
export const [updatedContactId, setUpdatedContactId] = createSignal<number>(-1);
